import type { AdminMetrics, RequestRecord } from './api'

function isoHoursAgo(hoursAgo: number) {
  return new Date(Date.now() - hoursAgo * 60 * 60 * 1000).toISOString()
}

export const DEMO_REQUESTS: RequestRecord[] = [
  {
    request_id: 'REQ-2026-0411-84721',
    workflow_id: 'loan_approval',
    status: 'APPROVED',
    attempt_count: 1,
    payload: { applicant_id: 'CUS-29841', amount: 120000, credit_score: 742, region: 'us-east' },
    response: { decision: 'APPROVED', apr: 8.2, limit: 120000 },
    processing_ms: 918,
    created_at: isoHoursAgo(1),
    updated_at: isoHoursAgo(1),
  },
  {
    request_id: 'REQ-2026-0411-84706',
    workflow_id: 'loan_approval',
    status: 'MANUAL_REVIEW',
    attempt_count: 2,
    payload: { applicant_id: 'CUS-18322', amount: 250000, credit_score: 661, region: 'us-west' },
    response: { decision: 'MANUAL_REVIEW' },
    failure_reason: 'Income verification mismatch between payroll and tax transcript',
    admin_note: 'Awaiting underwriter review',
    processing_ms: 1763,
    created_at: isoHoursAgo(2),
    updated_at: isoHoursAgo(1.5),
  },
  {
    request_id: 'REQ-2026-0411-84688',
    workflow_id: 'vendor_approval',
    status: 'REJECTED',
    attempt_count: 1,
    payload: { vendor_id: 'VND-4402', risk_score: 81, sanctions_hit: true },
    response: { decision: 'REJECTED' },
    failure_reason: 'Sanctions screening returned high-confidence match',
    processing_ms: 621,
    created_at: isoHoursAgo(3),
    updated_at: isoHoursAgo(3),
  },
  {
    request_id: 'REQ-2026-0411-84664',
    workflow_id: 'claim_processing',
    status: 'APPROVED',
    attempt_count: 1,
    payload: { claim_id: 'CLM-55219', amount: 8800, policy_age_months: 21 },
    response: { decision: 'APPROVED', payout_eta_days: 2 },
    processing_ms: 734,
    created_at: isoHoursAgo(4),
    updated_at: isoHoursAgo(4),
  },
  {
    request_id: 'REQ-2026-0411-84642',
    workflow_id: 'document_verification',
    status: 'FAILED',
    attempt_count: 3,
    payload: { document_id: 'DOC-91222', country: 'US', doc_type: 'passport' },
    response: { decision: 'FAILED' },
    failure_reason: 'OCR provider timeout after 3 retries',
    admin_note: 'Route to fallback provider',
    processing_ms: 5120,
    created_at: isoHoursAgo(5),
    updated_at: isoHoursAgo(4.6),
  },
  {
    request_id: 'REQ-2026-0411-84605',
    workflow_id: 'employee_onboarding',
    status: 'IN_PROGRESS',
    attempt_count: 1,
    payload: { employee_id: 'EMP-7721', location: 'Bangalore', grade: 'L3' },
    response: { step: 'background_check' },
    processing_ms: 302,
    created_at: isoHoursAgo(6),
    updated_at: isoHoursAgo(5.8),
  },
  {
    request_id: 'REQ-2026-0410-84571',
    workflow_id: 'fraud_check',
    status: 'APPROVED',
    attempt_count: 1,
    payload: { txn_id: 'TXN-1908123', velocity_24h: 2, ip_risk: 'low' },
    response: { decision: 'APPROVED', risk_band: 'LOW' },
    processing_ms: 463,
    created_at: isoHoursAgo(8),
    updated_at: isoHoursAgo(8),
  },
  {
    request_id: 'REQ-2026-0410-84536',
    workflow_id: 'claim_processing',
    status: 'PENDING',
    attempt_count: 1,
    payload: { claim_id: 'CLM-55107', amount: 43000, policy_age_months: 3 },
    response: { decision: 'PENDING', waiting_on: 'medical_report' },
    processing_ms: 125,
    created_at: isoHoursAgo(10),
    updated_at: isoHoursAgo(9.8),
  },
  {
    request_id: 'REQ-2026-0410-84490',
    workflow_id: 'vendor_approval',
    status: 'APPROVED',
    attempt_count: 1,
    payload: { vendor_id: 'VND-4301', risk_score: 22, sanctions_hit: false },
    response: { decision: 'APPROVED', tier: 'preferred' },
    processing_ms: 587,
    created_at: isoHoursAgo(12),
    updated_at: isoHoursAgo(12),
  },
  {
    request_id: 'REQ-2026-0409-84348',
    workflow_id: 'loan_approval',
    status: 'REJECTED',
    attempt_count: 1,
    payload: { applicant_id: 'CUS-11402', amount: 400000, credit_score: 598, region: 'us-central' },
    response: { decision: 'REJECTED' },
    failure_reason: 'Debt-to-income ratio exceeded policy threshold',
    processing_ms: 690,
    created_at: isoHoursAgo(24),
    updated_at: isoHoursAgo(24),
  },
  {
    request_id: 'REQ-2026-0409-84297',
    workflow_id: 'fraud_check',
    status: 'MANUAL_REVIEW',
    attempt_count: 2,
    payload: { txn_id: 'TXN-1907744', velocity_24h: 11, ip_risk: 'medium' },
    response: { decision: 'MANUAL_REVIEW' },
    failure_reason: 'Device fingerprint mismatch with prior account behavior',
    admin_note: 'Fraud ops analyst queued',
    processing_ms: 1180,
    created_at: isoHoursAgo(27),
    updated_at: isoHoursAgo(26.2),
  },
  {
    request_id: 'REQ-2026-0408-84110',
    workflow_id: 'document_verification',
    status: 'APPROVED',
    attempt_count: 2,
    payload: { document_id: 'DOC-90911', country: 'DE', doc_type: 'national_id' },
    response: { decision: 'APPROVED', confidence: 0.96 },
    processing_ms: 1420,
    created_at: isoHoursAgo(51),
    updated_at: isoHoursAgo(50.7),
  },
]

export const DEMO_ADMIN_METRICS: AdminMetrics = {
  total_requests: 12847,
  approval_rate: 0.67,
  rejection_rate: 0.18,
  pending_review: 534,
  failed: 76,
  avg_processing_time_ms: 1186,
  failure_rate_by_workflow: {
    loan_approval: 0.025,
    claim_processing: 0.018,
    document_verification: 0.044,
    vendor_approval: 0.012,
    employee_onboarding: 0.009,
    fraud_check: 0.031,
  },
  requests_by_workflow: {
    loan_approval: 4020,
    claim_processing: 2394,
    document_verification: 2148,
    vendor_approval: 1682,
    employee_onboarding: 1293,
    fraud_check: 1310,
  },
  status_breakdown: {
    APPROVED: 8610,
    REJECTED: 2312,
    MANUAL_REVIEW: 534,
    FAILED: 76,
    PENDING: 933,
    IN_PROGRESS: 382,
  },
  requests_last_7_days: [
    { date: 'Apr 05', count: 1634 },
    { date: 'Apr 06', count: 1712 },
    { date: 'Apr 07', count: 1698 },
    { date: 'Apr 08', count: 1765 },
    { date: 'Apr 09', count: 1821 },
    { date: 'Apr 10', count: 1889 },
    { date: 'Apr 11', count: 1944 },
  ],
}

export const DEMO_AUDIT_ENTRIES: Array<Record<string, unknown>> = [
  {
    timestamp: isoHoursAgo(0.2),
    request_id: 'REQ-2026-0411-84706',
    workflow_id: 'loan_approval',
    stage: 'risk_assessment',
    rule: 'credit_check',
    result: 'FAILED',
    explanation: 'Credit Check failed: bureau score below approval threshold.',
  },
  {
    timestamp: isoHoursAgo(0.7),
    request_id: 'REQ-2026-0411-84642',
    workflow_id: 'document_verification',
    stage: 'identity_verification',
    rule: 'document_ocr',
    result: 'TIMEOUT',
    explanation: 'Document OCR timed out after retry window expired.',
  },
  {
    timestamp: isoHoursAgo(1.1),
    request_id: 'REQ-2026-0411-84721',
    workflow_id: 'fraud_check',
    stage: 'risk_assessment',
    rule: 'risk_score',
    result: 'PASSED',
    explanation: 'Risk Score passed and request advanced to final decision.',
  },
  {
    timestamp: isoHoursAgo(4),
    request_id: 'REQ-2026-0411-84664',
    workflow_id: 'claim_processing',
    stage: 'fraud_triage',
    rule: 'duplicate_claim_window_30d',
    result: 'PASS',
    explanation: 'No prior similar claim in 30-day lookback window',
  },
  {
    timestamp: isoHoursAgo(5),
    request_id: 'REQ-2026-0411-84642',
    workflow_id: 'document_verification',
    stage: 'identity_verification',
    rule: 'ocr_provider_timeout_guard',
    result: 'FAIL',
    explanation: 'OCR dependency did not respond within 5s SLA',
  },
]

export function getDemoAuditForRequest(requestId: string) {
  if (requestId === 'REQ-2026-0411-84642') {
    return {
      rule_trace: [
        {
          stage: 'document_ingest',
          rule_id: 'supported_document_type',
          field: 'doc_type',
          operator: 'in',
          expected_value: ['passport', 'national_id', 'driver_license'],
          actual_value: 'passport',
          result: 'PASS',
          explanation: 'Document type is supported for automated processing',
        },
        {
          stage: 'identity_verification',
          rule_id: 'ocr_provider_timeout_guard',
          field: 'provider_latency_ms',
          operator: 'lt',
          expected_value: 5000,
          actual_value: 5000,
          result: 'FAIL',
          explanation: 'OCR dependency reached timeout threshold',
        },
      ],
      external_calls: [
        {
          timestamp: isoHoursAgo(5),
          stage: 'identity_verification',
          rule_id: 'ocr_primary_provider',
          result: 'FAILED',
          explanation: 'Timeout after exponential backoff',
          details: { attempt: 3, latency_ms: 5000, provider: 'vision-west-2' },
        },
      ],
    }
  }

  return {
    rule_trace: [
      {
        stage: 'risk_assessment',
        rule_id: 'credit_score_min_680',
        field: 'credit_score',
        operator: 'gte',
        expected_value: 680,
        actual_value: 742,
        result: 'PASS',
        explanation: 'Applicant exceeds credit threshold',
      },
      {
        stage: 'policy_check',
        rule_id: 'debt_to_income_max_45',
        field: 'dti_ratio',
        operator: 'lte',
        expected_value: 0.45,
        actual_value: 0.33,
        result: 'PASS',
        explanation: 'Debt-to-income ratio is within policy limits',
      },
    ],
    external_calls: [
      {
        timestamp: isoHoursAgo(1),
        stage: 'bureau_lookup',
        rule_id: 'credit_bureau_fetch',
        result: 'PASS',
        explanation: 'Credit bureau profile fetched successfully',
        details: { attempt: 1, latency_ms: 286, provider: 'bureau-us-east-1' },
      },
    ],
  }
}
